### ISSUE TITLE
Dúvidas e Sugestões (2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [olist/correios#122]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Espero que tenhamos uma resposta satisfatória e um UPGRADE.

**Comment by rougeth** [comment]
@PauloBoaventura esse projeto é feito em **Python**. Você pode [ver aqui](https://github.com/olist/correios/tree/master/documentation) os documentos que foram usados como base de conhecimento. 

Nós, da @olist, usamos esta lib para integrar com os Correios, então, o código está atualizado com as normativas/regras.

**Comment by PauloBoaventura** [comment]
Olá @rougeth 
Obrigado pelo comentario.
O que necessito é algo que faça calculo do frete e inserir no final do pedido. Para plataforma Magento 1.9 ou 2.1... 

Sabe me dizer se posso fazer isso com esta?
Abs

**Comment by rougeth** [comment]
Acredito que não @PauloBoaventura.
