### ISSUE TITLE
Zeep

### ISSUE THREAD

**Issue by jairhenrique** [olist/correios#84]
It would be nice to use [zeep](http://docs.python-zeep.org/) instead of `suds`!
Zeep has support to `aiohttp` and this is so cool!
What do you think about this?

```python
import logging

from requests import Session
from zeep import Client, Transport


logger = logging.getLogger(__name__)


class SoapClient(Client):

    def __init__(
        self,
        wsdl,
        cert=None,
        verify=True,
        timeout=8,
        username=None,
        password=None,
        *args,
        **kwargs
    ):
        session = Session()
        session.cert = cert
        session.verify = verify
        session.timeout = timeout
        session.auth = (username, password)
        session.headers.update({"Content-Type": "text/xml;charset=UTF-8"})

        transport = Transport(
            operation_timeout=timeout,
            session=session
        )

        super().__init__(wsdl=wsdl, transport=transport, **kwargs)
```

**Comment by georgeyk** [comment]
It certainly looks good. I think `suds` was picked because from previous experience, but @osantana could say more about this.
Are you willing to replace suds ?

**Comment by osantana** [comment]
When I started correios development python-zeep has a poor documentation and a extremely complex code with lots of "meta" constructions. Besides that I already known how to use suds because I used it in previous projects.

But I'd be happy with contributions that enables correios lib to use asyncio/aiohttp.

**Comment by jairhenrique** [comment]
@georgeyk @osantana this code already "replaces" `suds`, but the most of client tests broke. I need some more free time to analyse and improve client code.

**Comment by osantana** [comment]
> this code already "replaces" suds, but the most of client tests broke.

yep. 

We need to implement a client class with "a" methods (`async def`) with `await` method calls too.

**Comment by osantana** [comment]
I'll close this issue but feel free to reopen it if we need to discuss more about 'async' interface.
