### ISSUE TITLE
Problem with wsdl read time

### ISSUE THREAD

**Issue by gilmarsoares-luizalabs** [olist/correios#87]
We are having problems with wsdl reading time.
When creating an instance of the Mail class, the flow is reading the wsdl in the mail endpoint.
It would be better if reading this wsdl could be local file, it would improve the response time to instantiate the object.

**Comment by jairhenrique** [comment]
fixed on https://github.com/olist/correios/pull/90

**Comment by osantana** [comment]
Closing this issue.
